"""add_activo_column_and_role_constraint

Revision ID: 9635dcd4514d
Revises: b6fb1570e159
Create Date: 2026-06-06 16:18:06.530803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9635dcd4514d'
down_revision: Union[str, Sequence[str], None] = 'b6fb1570e159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('envios', 'fecha_limite',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('historial_notificaciones', 'canal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'correo'::text"))
    op.alter_column('historial_notificaciones', 'motivo_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('historial_notificaciones_envio_id_fkey'), 'historial_notificaciones', type_='foreignkey')
    op.create_foreign_key(None, 'historial_notificaciones', 'envios', ['envio_id'], ['id'])
    op.alter_column('notificaciones_app', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notificaciones_app', 'usuario_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('idx_notificaciones_leida'), table_name='notificaciones_app')
    op.drop_index(op.f('idx_notificaciones_usuario'), table_name='notificaciones_app')
    op.create_index(op.f('ix_notificaciones_app_id'), 'notificaciones_app', ['id'], unique=False)
    op.drop_constraint(op.f('notificaciones_app_usuario_id_fkey'), 'notificaciones_app', type_='foreignkey')
    op.create_foreign_key(None, 'notificaciones_app', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('plantillas_notificacion', 'estado_disparador',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('en sucursal', 'en transito', 'cancelado', 'entregado', name='estadoenvio', native_enum=False),
               existing_nullable=False)
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), server_default='true'))
    op.alter_column('usuarios', 'activo', nullable=False, server_default=None)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('repartidor', 'operador', 'supervisor', 'administrador', name='roles_usuario', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'rol',
               existing_type=sa.Enum('repartidor', 'operador', 'supervisor', 'administrador', name='roles_usuario', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('usuarios', 'activo')
    op.alter_column('plantillas_notificacion', 'estado_disparador',
               existing_type=sa.Enum('en sucursal', 'en transito', 'cancelado', 'entregado', name='estadoenvio', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'notificaciones_app', type_='foreignkey')
    op.create_foreign_key(op.f('notificaciones_app_usuario_id_fkey'), 'notificaciones_app', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notificaciones_app_id'), table_name='notificaciones_app')
    op.create_index(op.f('idx_notificaciones_usuario'), 'notificaciones_app', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_notificaciones_leida'), 'notificaciones_app', ['leida'], unique=False)
    op.alter_column('notificaciones_app', 'usuario_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('notificaciones_app', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'historial_notificaciones', type_='foreignkey')
    op.create_foreign_key(op.f('historial_notificaciones_envio_id_fkey'), 'historial_notificaciones', 'envios', ['envio_id'], ['id'], ondelete='CASCADE')
    op.alter_column('historial_notificaciones', 'motivo_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('historial_notificaciones', 'canal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'correo'::text"))
    op.alter_column('envios', 'fecha_limite',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
