"""Agregar columna prioridad a envios

Revision ID: 9c665890fc5d
Revises: 
Create Date: 2026-05-31 19:06:19.130926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c665890fc5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envios', sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridadenvio', native_enum=False), nullable=False, server_default='baja'))
    op.drop_column('historial', 'motivo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial', sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('envios', 'prioridad')
    # ### end Alembic commands ###
