"""agregar columna motivo

Revision ID: c4069ec53471
Revises: 
Create Date: 2026-05-22 16:58:33.761126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4069ec53471'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial', sa.Column('motivo', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'perfiles_empresa', ['razon_social'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfiles_empresa', type_='unique')
    op.drop_column('historial', 'motivo')
    # ### end Alembic commands ###
